name: First Interaction

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thanks for creating your first issue! We’ll check it soon."
          pr-message: "🎉 Thanks for your first pull request! Someone will review it shortly."
